2025-02-17 11:20:23.115894 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:23.183140 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:23.301190 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:23.546859 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:23.758463 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:23.835349 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.117705 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.272252 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.477936 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.547604 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.616478 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.782493 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:24.942917 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.030393 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.105386 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.275210 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.340170 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.479552 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.543227 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.603841 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.763894 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.823424 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:25.929992 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.080583 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.161393 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.234052 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.367982 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.455562 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.580410 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.650052 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.758754 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:26.881660 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
2025-02-17 11:20:27.000112 ---> Exception: 'tensorflow.python.framework.ops.EagerTensor' object is not callable.
